from sqlalchemy import BigInteger, Column, Double, MetaData, PrimaryKeyConstraint, Table, Text

metadata = MetaData()


t_master_dataset_v3 = Table(
    'master_dataset_v3', metadata,
    Column('시도_명칭', Text),
    Column('구', Text, primary_key=True),
    Column('행정동명', Text, primary_key=True),
    Column('행정동ID_8자리', Text),
    Column('hnet_code', Text),
    Column('면적_m2', Double(53)),
    Column('면적_km2', Double(53)),
    Column('CCTV_수', Double(53)),
    Column('버스정류장_수', Double(53)),
    Column('의료기관_수', Double(53)),
    Column('학교_수', Double(53)),
    Column('학원_수', Double(53)),
    Column('쓰레기통_수', Double(53)),
    Column('건물_수', Double(53)),
    Column('공원_수', Double(53)),
    Column('대형점포_수', Double(53)),
    Column('경찰관서_수', Double(53)),
    Column('소방관서_수', Double(53)),
    Column('지하철역_수', Double(53)),
    Column('점포_수', Double(53)),
    Column('범죄발생_구', BigInteger),
    Column('소음민원_구', BigInteger),
    Column('CCTV설치_구', BigInteger),
    Column('녹지면적_구', BigInteger),
    Column('학교녹지면적_구', BigInteger),
    Column('재해위험지구_구', BigInteger),
    Column('소음_주간_구', Double(53)),
    Column('소음_야간_구', Double(53)),
    Column('초미세먼지_구', Double(53)),
    Column('CCTV_밀도', Double(53)),
    Column('버스정류장_밀도', Double(53)),
    Column('의료기관_밀도', Double(53)),
    Column('학교_밀도', Double(53)),
    Column('학원_밀도', Double(53)),
    Column('쓰레기통_밀도', Double(53)),
    Column('건물_밀도', Double(53)),
    Column('공원_밀도', Double(53)),
    Column('대형점포_밀도', Double(53)),
    Column('경찰관서_밀도', Double(53)),
    Column('소방관서_밀도', Double(53)),
    Column('지하철역_밀도', Double(53)),
    Column('점포_밀도', Double(53)),
    Column('문화시설_수', BigInteger),
    Column('공연시설_수', BigInteger),
    Column('기타문화_수', BigInteger),
    Column('도서관_수', BigInteger),
    Column('전시시설_수', BigInteger),
    Column('무료문화시설_수', BigInteger),
    Column('문화시설_밀도', Double(53)),
    Column('공연시설_밀도', Double(53)),
    Column('기타문화_밀도', Double(53)),
    Column('도서관_밀도', Double(53)),
    Column('전시시설_밀도', Double(53)),
    Column('무료문화시설_밀도', Double(53)),
    Column('총전입', BigInteger),
    Column('총전출', BigInteger),
    Column('순이동', BigInteger),
    Column('전입률_퍼센트', Double(53)),
    Column('전출률_퍼센트', Double(53)),
    Column('이동률_퍼센트', Double(53)),
    Column('순이동률_퍼센트', Double(53)),
    Column('거주안정성_점수', Double(53)),
    Column('단독다가구_매매_매매가', Double(53)),
    Column('아파트_매매_매매가', Double(53)),
    Column('연립다세대_매매_매매가', Double(53)),
    Column('오피스텔_매매_매매가', Double(53)),
    Column('단독다가구_월세_보증금', Double(53)),
    Column('단독다가구_전세_보증금', Double(53)),
    Column('아파트_월세_보증금', Double(53)),
    Column('아파트_전세_보증금', Double(53)),
    Column('연립다세대_월세_보증금', Double(53)),
    Column('연립다세대_전세_보증금', Double(53)),
    Column('오피스텔_월세_보증금', Double(53)),
    Column('오피스텔_전세_보증금', Double(53)),
    Column('단독다가구_월세_월세', Double(53)),
    Column('아파트_월세_월세', Double(53)),
    Column('연립다세대_월세_월세', Double(53)),
    Column('오피스텔_월세_월세', Double(53)),
    Column('단독다가구_매매_㎡당가', Double(53)),
    Column('단독다가구_전세_㎡당가', Double(53)),
    Column('아파트_매매_㎡당가', Double(53)),
    Column('아파트_전세_㎡당가', Double(53)),
    Column('연립다세대_매매_㎡당가', Double(53)),
    Column('연립다세대_전세_㎡당가', Double(53)),
    Column('오피스텔_매매_㎡당가', Double(53)),
    Column('오피스텔_전세_㎡당가', Double(53)),
    PrimaryKeyConstraint('구', '행정동명', name='master_dataset_v3_pkey')
)

t_대규모점포_전통시장_통합_최종 = Table(
    '대규모점포_전통시장_통합_최종', metadata,
    Column('이름', Text),
    Column('구', Text),
    Column('행정동', Text),
    Column('주소', Text),
    Column('시설유형', Text),
    Column('점포구분명', Text),
    Column('형태', Text),
    Column('건물연면적', Double(53)),
    Column('점포수', Double(53)),
    Column('위도', Double(53)),
    Column('경도', Double(53))
)

t_문화시설_개별_행정동매칭 = Table(
    '문화시설_개별_행정동매칭', metadata,
    Column('문화시설명', Text),
    Column('주제분류', Text),
    Column('문화분류', Text),
    Column('주소', Text),
    Column('자치구', Text),
    Column('행정동명', Text),
    Column('행정동ID_8자리', Text),
    Column('위도', Double(53)),
    Column('경도', Double(53)),
    Column('무료여부', Text),
    Column('관람시간', Text),
    Column('휴관일', Text),
    Column('객석수', Text),
    Column('전화번호', Text),
    Column('홈페이지', Text),
    Column('매칭거리_m', Double(53)),
    Column('매칭품질', Text)
)

t_서울시_25개구_도시공원정보_통합_행정동포함 = Table(
    '서울시_25개구_도시공원정보_통합_행정동포함', metadata,
    Column('구', Text),
    Column('공원명', Text),
    Column('공원구분', Text),
    Column('동', Text),
    Column('소재지지번주소', Text),
    Column('행정동', Text),
    Column('위도', Double(53)),
    Column('경도', Double(53)),
    Column('공원면적', Text)
)

t_시세_지역별_전처리 = Table(
    '시세_지역별_전처리', metadata,
    Column('지역명', Text),
    Column('자치구명', Text),
    Column('지역종류', Text),
    Column('위도', Double(53)),
    Column('경도', Double(53)),
    Column('건물용도', Text),
    Column('거래유형', Text),
    Column('거래건수', BigInteger),
    Column('신뢰등급', Text),
    Column('출처', Text),
    Column('매매가', Double(53)),
    Column('매매가_25', Double(53)),
    Column('매매가_75', Double(53)),
    Column('보증금', Double(53)),
    Column('보증금_25', Double(53)),
    Column('보증금_75', Double(53)),
    Column('월임대료', Double(53)),
    Column('면적_중앙값', Double(53)),
    Column('면적_25', Double(53)),
    Column('면적_75', Double(53)),
    Column('㎡당_중앙값', Double(53)),
    Column('행정동ID_8자리', Text)
)

t_의료_전처리 = Table(
    '의료_전처리', metadata,
    Column('기관구분', Text),
    Column('자치구', Text),
    Column('행정동', Text),
    Column('행정동코드', Text),
    Column('시설명', Text),
    Column('도로명주소', Text),
    Column('위도', Double(53)),
    Column('경도', Double(53))
)

t_학원_전처리 = Table(
    '학원_전처리', metadata,
    Column('자치구', Text),
    Column('학원/교습소', Text),
    Column('학원명', Text),
    Column('분야명', Text),
    Column('교습계열명', Text),
    Column('정원합계', BigInteger),
    Column('도로명주소', Text),
    Column('위도', Double(53)),
    Column('경도', Double(53)),
    Column('행정동코드', Text),
    Column('행정동', Text)
)

t_행정동별_세대원수_전처리 = Table(
    '행정동별_세대원수_전처리', metadata,
    Column('구', Text, primary_key=True),
    Column('동', Text),
    Column('행정동명', Text, primary_key=True),
    Column('전체세대', BigInteger),
    Column('1인세대', BigInteger),
    Column('2인세대', BigInteger),
    Column('3인세대', BigInteger),
    Column('4인세대', BigInteger),
    Column('5인이상세대', BigInteger),
    Column('1인_비율', Double(53)),
    Column('2인_비율', Double(53)),
    Column('3인_비율', Double(53)),
    Column('4인_비율', Double(53)),
    Column('5인이상_비율', Double(53)),
    Column('평균가구원수', Double(53)),
    PrimaryKeyConstraint('구', '행정동명', name='행정동별_세대원수_전처리_pkey')
)
